drop table BUSINESS;
drop table REVIEWS;
drop table AUTHOR;
drop table BELONGS;
drop table YELP_USER;
drop table CHECKIN;
drop table PHOTO;
drop table RATE;
drop table BUSINESS_CATEGORY;
drop table Business;
drop table PHOTO_AUTHOR ;